export const DEFAULT_BLOG_POSTS = [
  {
    id: 'p1',
    title: '5 Claves de Nutrición para Aumentar Masa Muscular sin Ganar Grasa',
    slug: 'claves-nutricion-aumentar-masa-muscular',
    excerpt: 'Aprende a estructurar tus calorías, macronutrientes y momentos de comida para maximizar la síntesis proteica y el rendimiento.',
    content: `Ganar masa muscular de forma limpia no requiere comer todo lo que encuentres a tu paso. Se trata de entregar a tus músculos los nutrientes exactos para reparar las fibras rotas durante el entrenamiento en Beast Training.\n\n### 1. El superávit calórico controlado\nPara construir tejido muscular nuevo, tu cuerpo necesita un excedente energético, pero un superávit de entre 250 y 400 kcal diarias sobre tu mantenimiento es suficiente. Esto minimiza la acumulación de tejido graso.\n\n### 2. Prioriza la proteína en cada comida\nConsume entre 1.8 y 2.2 gramos de proteína por kilogramo de peso corporal al día. Distribúyela en 3 a 5 tomas con fuentes de alto valor biológico: pechuga de pollo, huevos enteros, pescado, vacuno magro y proteína aislada.\n\n### 3. Carbohidratos: el combustible del entrenamiento pesado\nNo le temas a los carbohidratos. La avena, el arroz, las papas y la fruta reponen el glucógeno muscular y te permiten levantar con mayor intensidad en cada serie.\n\n### 4. Hidratación y electrolitos\nUn músculo deshidratado pierde hasta un 15% de su capacidad de fuerza. Bebe al menos 35-40 ml de agua por kg de peso al día.\n\n*Consejo de Pelu:* La constancia supera al talento. Si comes con disciplina 6 días a la semana, tus resultados hablarán por sí solos.`,
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Nutrición',
    published_at: '2026-08-31T12:00:00Z',
  },
  {
    id: 'p2',
    title: 'Sobrecarga Progresiva: El Secreto Real para Volverte Fuerte',
    slug: 'sobrecarga-progresiva-secreto-fuerza',
    excerpt: 'Descubre qué es la sobrecarga progresiva y cómo aplicarla en cada sesión de entrenamiento para no estancarte nunca.',
    content: `¿Llevas meses levantando el mismo peso con las mismas repeticiones y no ves cambios? El principio número uno del crecimiento muscular y la fuerza es la **Sobrecarga Progresiva**.\n\n### ¿Qué es la sobrecarga progresiva?\nEs el aumento gradual del estrés impuesto al sistema neuromuscular a lo largo del tiempo. Si tu cuerpo no recibe un estímulo superior al que ya está adaptado, no tiene ninguna razón biológica para crecer.\n\n### 4 Formas de aplicar sobrecarga progresiva:\n1. **Aumentar el peso:** Subir 1 a 2.5 kg a la barra manteniendo la técnica perfecta.\n2. **Aumentar las repeticiones:** Si hacías 8 repeticiones con 60 kg, busca llegar a 10 u 11 repeticiones con el mismo peso.\n3. **Aumentar las series:** Pasar de 3 a 4 series efectivas en un ejercicio compuesto.\n4. **Mejorar el control del movimiento:** Aumentar el tiempo bajo tensión (bajada lenta y controlada de 3 segundos).\n\n*Consejo de Pelu:* Lleva un cuaderno o app con tus marcas de cada semana. Lo que no se mide, no se puede mejorar.`,
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Fuerza',
    published_at: '2026-08-30T12:00:00Z',
  },
  {
    id: 'p3',
    title: 'Cómo Evitar Lesiones: Calentamiento Dinámico y Movilidad',
    slug: 'como-evitar-lesiones-calentamiento-dinamico',
    excerpt: 'Conoce la rutina de calentamiento articular y activación neuromuscular que debes hacer antes de tocar una barra.',
    content: `El calentamiento no es solo subirse 5 minutos a la trotadora. Una correcta preparación previa eleva la temperatura corporal, lubrica las articulaciones y activa el sistema nervioso central.\n\n### ¿Por qué evitar estiramientos estáticos antes de levantar pesado?\nEstirar un músculo en frío de forma estática por más de 30 segundos relaja los husos musculares y puede reducir temporalmente tu capacidad de generar fuerza explosiva.\n\n### El Protocolo RAMP para antes de entrenar:\n- **R (Raise):** Elevar temperatura corporal y ritmo cardíaco (saltos, remo suave o trote suave 3-4 min).\n- **A (Activate):** Activar glúteos, core y manguito rotador con bandas elásticas.\n- **M (Mobilize):** Movilidad dinámica de tobillos, caderas y columna torácica.\n- **P (Potentiate):** Series de aproximación en el ejercicio principal con peso progresivo.\n\n*Consejo de Pelu:* 10 minutos de buen calentamiento te ahorrarán 6 meses de recuperación por lesión en el hombro o la espalda baja.`,
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Prevención',
    published_at: '2026-08-29T12:00:00Z',
  },
  {
    id: 'p4',
    title: 'El Poder del Descanso y Sueño en la Recuperación Muscular',
    slug: 'poder-descanso-sueno-recuperacion-muscular',
    excerpt: 'Los músculos no crecen en el gimnasio, crecen mientras duermes. Aprende a optimizar tu descanso para rendir al 100%.',
    content: `En el gimnasio rompemos fibras musculares y generamos estrés fisiológico; es durante el sueño profundo cuando el cuerpo libera la hormona de crecimiento (GH) y sintetiza nuevas proteínas para reparar los tejidos.\n\n### ¿Qué pasa cuando duermes menos de 6 horas?\n- Se elevan los niveles de cortisol (hormona del estrés y catabolismo muscular).\n- Disminuye la sensibilidad a la insulina, aumentando la propensión a acumular grasa corporal.\n- Aumenta la ghrelina (hormona del apetito), provocando antojos de comida chatarra.\n- Disminuye el foco y los reflejos durante el levantamiento.\n\n### Hábitos para dormir como una bestia:\n1. Duerme entre 7 y 9 horas continuas.\n2. Evita pantallas y luces azules 45 minutos antes de acostarte.\n3. Mantén tu habitación fresca y completamente a oscuras.\n4. Cena ligero al menos 2 horas antes de dormir.\n\n*Consejo de Pelu:* Si entrenas como una bestia pero duermes 4 horas, estás perdiendo más de la mitad de tu progreso.`,
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Recuperación',
    published_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'p5',
    title: 'HIIT vs Cardio Tradicional: ¿Cuál Quema Más Grasa?',
    slug: 'hiit-vs-cardio-tradicional-quemar-grasa',
    excerpt: 'Comparamos el entrenamiento por intervalos de alta intensidad con el cardio de baja intensidad para optimizar tu tiempo.',
    content: `Existe un debate eterno en el mundo fitness: ¿es mejor trotar a ritmo suave por 45 minutos o realizar 20 minutos de sprints de alta intensidad (HIIT)?\n\n### Entrenamiento por Intervalos (HIIT):\n- **Ventajas:** Máxima quema calórica en poco tiempo, efecto EPOC (continúas quemando calorías hasta 24 horas después) y preservación de masa muscular.\n- **Frecuencia ideal:** 2 a 3 sesiones semanales de 15 a 20 minutos.\n\n### Cardio Continuo de Baja Intensidad (LISS):\n- **Ventajas:** Bajo impacto articular, excelente para recuperar entre días pesados de musculación y fácil de sostener.\n- **Frecuencia ideal:** Caminatas diarias de 8.000 a 10.000 pasos.\n\n### El Veredicto:\nNo son enemigos, son complementarios. Usa el HIIT para elevar tu capacidad cardiovascular y el LISS diario para mantenerte activo sin sobrecargar tus articulaciones.\n\n*Consejo de Pelu:* El mejor cardio es el que disfrutas y puedes mantener con disciplina mes a mes.`,
    image_url: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Cardio',
    published_at: '2026-08-27T12:00:00Z',
  },
  {
    id: 'p6',
    title: 'Guía Básica de Suplementos: Qué Sirve de Verdad',
    slug: 'guia-suplementos-que-sirve-y-que-no',
    excerpt: 'Ahorra dinero y enfócate en los suplementos con evidencia científica sólida de efectividad y seguridad.',
    content: `La industria de los suplementos genera millones prometiendo resultados mágicos. Sin embargo, solo un puñado cuenta con respaldo científico contundente de Grado A.\n\n### Los que SÍ funcionan con evidencia comprobada:\n1. **Creatina Monohidrato (Creapure):** El suplemento más estudiado del mundo. Aumenta la fuerza, la potencia explosiva y la hidratación intracelular. Dosis: 3 a 5 gramos diarios todos los días.\n2. **Proteína de Suero (Whey Protein):** Excelente herramienta de conveniencia para alcanzar tu requerimiento diario de proteína de manera rápida y deliciosa.\n3. **Cafeína:** Aumenta la concentración, reduce la percepción del esfuerzo y mejora el rendimiento anaeróbico.\n4. **Omega 3 y Vitamina D3:** Fundamentales para la salud articular, cardiovascular y hormonal.\n\n### Los que puedes ahorrarte:\n- Quemadores de grasa milagrosos (la mayoría son solo cafeína con diuréticos).\n- BCAAs si ya consumes suficiente proteína diaria.\n- Potenciadores de testosterona en pastillas (no tienen evidencia real).\n\n*Consejo de Pelu:* Ningún suplemento compensa una mala dieta o un entrenamiento sin intensidad. Primero la comida real, luego los suplementos.`,
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1200&auto=format&fit=crop',
    author: 'Pelu',
    category: 'Suplementación',
    published_at: '2026-08-26T12:00:00Z',
  },
];
